// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationDistributionApp.Infrastructure;

#nullable disable

namespace OperationDistributionApp.Infrastructure.Migrations
{
    [DbContext(typeof(OperationDistributionAppContext))]
    partial class OperationDistributionAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Name = "John",
                            Surname = "Smith"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Name = "Emily",
                            Surname = "Johnson"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Name = "Michael",
                            Surname = "Williams"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Name = "Sarah",
                            Surname = "Jones"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Name = "David",
                            Surname = "Brown"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Name = "Jennifer",
                            Surname = "Wilson"
                        });
                });

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.History", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OperationID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OperationID");

                    b.ToTable("Histories");

                    b.HasData(
                        new
                        {
                            HistoryID = 1,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(956),
                            Difficulty = 1,
                            EmployeeID = 1,
                            IsActive = true,
                            OperationID = 1
                        },
                        new
                        {
                            HistoryID = 2,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(998),
                            Difficulty = 2,
                            EmployeeID = 2,
                            IsActive = true,
                            OperationID = 2
                        },
                        new
                        {
                            HistoryID = 3,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(999),
                            Difficulty = 3,
                            EmployeeID = 3,
                            IsActive = true,
                            OperationID = 3
                        },
                        new
                        {
                            HistoryID = 4,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(1000),
                            Difficulty = 4,
                            EmployeeID = 4,
                            IsActive = true,
                            OperationID = 4
                        },
                        new
                        {
                            HistoryID = 5,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(1002),
                            Difficulty = 5,
                            EmployeeID = 5,
                            IsActive = true,
                            OperationID = 5
                        },
                        new
                        {
                            HistoryID = 6,
                            CreatedAt = new DateTime(2023, 8, 1, 22, 46, 57, 102, DateTimeKind.Local).AddTicks(1003),
                            Difficulty = 6,
                            EmployeeID = 6,
                            IsActive = true,
                            OperationID = 6
                        });
                });

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationID"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperationID");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            OperationID = 1,
                            Difficulty = 1,
                            Name = "Welding Chassis"
                        },
                        new
                        {
                            OperationID = 2,
                            Difficulty = 2,
                            Name = "Assembling Engine Blocks"
                        },
                        new
                        {
                            OperationID = 3,
                            Difficulty = 3,
                            Name = "Installing Wiring Harnesses"
                        },
                        new
                        {
                            OperationID = 4,
                            Difficulty = 4,
                            Name = "Attaching Body Panels"
                        },
                        new
                        {
                            OperationID = 5,
                            Difficulty = 5,
                            Name = "Painting Car Bodies"
                        },
                        new
                        {
                            OperationID = 6,
                            Difficulty = 6,
                            Name = "Fitting Interior Components"
                        });
                });

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.History", b =>
                {
                    b.HasOne("OperationDistributionApp.Domain.Entities.Employee", "Employee")
                        .WithMany("Histories")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationDistributionApp.Domain.Entities.Operation", "Operation")
                        .WithMany("Histories")
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("OperationDistributionApp.Domain.Entities.Operation", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
